<?php


namespace app\controllers;


use yii\web\Controller;

class AppController extends Controller
{
    // function that runs before action function runs
    public function beforeAction($action)
    {
        // register meta tags that will be displayed in header
        $this->view->registerMetaTag(['author' => 'Igor Peshkov']);
        $this->view->registerMetaTag(['editor' => 'JetBrains Phpstorm']);
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'Yii2, Framework, Learning']);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}