<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class TestController extends Controller
{
    // change layout for this controller
    public $layout = 'basic';

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        // check if Ajax request
        if (Yii::$app->request->isAjax) {
            $response = [
                'success' => TRUE
            ];
            return $this->asJson($response);
        }

        return $this->render('index');
    }
}